apiVersion: v2
appVersion: 1.6.0
name: gateway-api-bundle
description: Gateway API bundle
home: https://github.com/giantswarm/gateway-api-bundle
icon: https://s.giantswarm.io/app-icons/gateway-api/1/light.svg
version: 1.6.0
annotations:
  application.giantswarm.io/team: cabbage
